### ISSUE TITLE
Strict errors in PHP 5.4

### ISSUE THREAD

**Issue by marianofino** [rchavik/sites#4]
When I activate the plugin in PHP 5.4, it throws this errors:
- Non-static method Sites::currentSite() should not be called statically, assuming $this from incompatible context
- Non-static method Sites::getInstance() should not be called statically, assuming $this from incompatible context
- Declaration of SitesHelper::beforeRender() should be compatible with Helper::beforeRender($viewFile)

I will check the code and try to fix it...

**Comment by rchavik** [comment]
thanks, that would be nice.  looking forward for your patch.

**Comment by marianofino** [comment]
done ;)
